# Generated by Django 5.1.6 on 2025-02-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateavailability',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.candidate'),
        ),
        migrations.AlterField(
            model_name='intervieweravailability',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.interviewer'),
        ),
        migrations.AddConstraint(
            model_name='candidateavailability',
            constraint=models.UniqueConstraint(fields=('candidate', 'start_time', 'end_time'), name='unique_candidate_availability'),
        ),
        migrations.AddConstraint(
            model_name='intervieweravailability',
            constraint=models.UniqueConstraint(fields=('interviewer', 'start_time', 'end_time'), name='unique_interviewer_availability'),
        ),
    ]
